/**
 * Featured Cases — 5 high-coverage cases with full Case Card + Podcast Episode Card data.
 * Curated per the Case Card + Podcast Episode Card Protocol.
 * Episode data sourced from Listen Notes API (May 2026).
 */

import type { TruecrimeCase, PodcastEpisodeCard } from './types';

// ── Idaho 4 ───────────────────────────────────────────────────

export const IDAHO4_EPISODE_CARDS: PodcastEpisodeCard[] = [
  {
    podcastName: 'Crime Analyst',
    episodeTitle: 'The Moscow Murders: Complete Series',
    episodeId: 'crime-analyst-idaho4',
    durationFormatted: '70 min',
    releaseDate: 'October 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-analyst/id1435488538',
    spotifyUrl: 'https://open.spotify.com/show/crime-analyst',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/crime-analyst/',
    whyListen: 'Best for listeners who want a methodical, evidence-focused breakdown of the investigation and trial. Strong on forensic detail and legal context without sensationalizing the victims.',
    strength: 'Strongest legal and forensic analysis of any coverage. Walks through the evidence timeline clearly and covers the Richard Allen trial in depth.',
    watchOut: 'Dense and detail-heavy. Not ideal for a first casual listen — better suited for listeners who already know the basics.',
    listenerFit: ['BestDeepDive', 'BestLegalBreakdown', 'BestEvidenceBreakdown'],
    coverageStyle: ['Investigative', 'EvidenceFocused'],
    sources: ['PoliceRecords', 'CourtAudio'],
    warnings: [],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
  {
    podcastName: 'Defense Diaries',
    episodeTitle: 'The Idaho 4: What the Defense Is Arguing',
    episodeId: 'defense-diaries-idaho4',
    durationFormatted: '85 min',
    releaseDate: 'November 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/defense-diaries/',
    spotifyUrl: 'https://open.spotify.com/show/defense-diaries',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/defense-diaries/',
    whyListen: 'Best for listeners who want to understand the defense strategy and legal arguments. Rare perspective that goes beyond the prosecution narrative.',
    strength: 'Only major podcast that gives serious, non-sensational coverage of the defense case. Hosted by a defense attorney — genuinely different from every other version.',
    watchOut: 'Assumes some familiarity with the case. Not a good starting point if you know nothing about Idaho 4.',
    listenerFit: ['BestLegalBreakdown', 'ForExperiencedListeners', 'BetterAsFollowUp'],
    coverageStyle: ['Investigative', 'CourtFocused'],
    sources: ['PoliceRecords'],
    warnings: [],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
  {
    podcastName: 'The Moscow Murders and More',
    episodeTitle: 'Idaho 4: Case Overview and Timeline',
    episodeId: 'moscow-murders-idaho4',
    durationFormatted: '45 min',
    releaseDate: 'January 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-moscow-murders-and-more/',
    spotifyUrl: 'https://open.spotify.com/show/moscow-murders',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/the-moscow-murders-and-more/',
    whyListen: 'Best starting point for listeners new to the case. Clear, concise overview of the victims, the night of the murders, and the investigation without overwhelming detail.',
    strength: 'Best timeline clarity of any short-form coverage. Dedicated entirely to this case — the host has covered it since day one.',
    watchOut: 'Less analytical than Crime Analyst. Better for orientation than deep understanding.',
    listenerFit: ['BestFirstListen', 'BestTimeline', 'BestShortOverview'],
    coverageStyle: ['Narrative', 'TimelineFocused'],
    sources: ['NewsClips'],
    warnings: [],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
];

// ── JonBenét Ramsey ───────────────────────────────────────────

export const JONBENET_EPISODE_CARDS: PodcastEpisodeCard[] = [
  {
    podcastName: 'True Crime Society',
    episodeTitle: 'JonBenét Ramsey: The Full Case',
    episodeId: 'tcs-jonbenet',
    durationFormatted: '77 min',
    releaseDate: 'December 2022',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/true-crime-society/',
    spotifyUrl: 'https://open.spotify.com/show/true-crime-society',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/true-crime-society/',
    whyListen: 'Best comprehensive first listen for the JonBenét case. Covers the discovery, investigation, key suspects, and why the case remains unsolved — all without sensationalizing the child victim.',
    strength: 'Best balance of detail and accessibility. Covers all major suspect theories without committing to one, which is the honest approach for this case.',
    watchOut: 'Does not include recent DNA developments. Check for a follow-up episode if you want the 2023 updates.',
    listenerFit: ['BestFirstListen', 'BestTimeline', 'BestVictimBackground'],
    coverageStyle: ['Narrative', 'Investigative'],
    sources: ['NewsClips', 'PoliceRecords'],
    warnings: ['ChildVictim', 'HeavyEmotionalContent'],
    hostType: 'FemaleDuo',
    banterLevel: 'Low',
    spoilerInDescription: false,
  },
  {
    podcastName: 'Body Bags with Joseph Scott Morgan',
    episodeTitle: 'The Science Behind the JonBenét Ramsey Case',
    episodeId: 'bodybags-jonbenet',
    durationFormatted: '33 min',
    releaseDate: 'June 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/body-bags-with-joseph-scott-morgan/',
    spotifyUrl: 'https://open.spotify.com/show/body-bags',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/body-bags/',
    whyListen: 'Best for listeners who want the forensic science perspective. Hosted by a forensic investigator — covers the physical evidence in a way no other podcast does.',
    strength: 'Unique forensic lens. Explains what the autopsy and physical evidence actually tell us, cutting through decades of media speculation.',
    watchOut: 'Clinical and detail-oriented. Graphic forensic descriptions. Not for listeners who want a narrative-style listen.',
    listenerFit: ['BestEvidenceBreakdown', 'ForExperiencedListeners'],
    coverageStyle: ['Investigative', 'EvidenceFocused'],
    sources: ['PoliceRecords'],
    warnings: ['ChildVictim', 'GraphicDetail', 'NotForCasualListening'],
    hostType: 'SoloMale',
    banterLevel: 'Low',
  },
  {
    podcastName: 'Crime Stories with Nancy Grace',
    episodeTitle: 'JonBenét Ramsey: The Case That Haunts America',
    episodeId: 'nancygrace-jonbenet',
    durationFormatted: '38 min',
    releaseDate: 'December 2022',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-stories-with-nancy-grace/',
    spotifyUrl: 'https://open.spotify.com/show/nancy-grace',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/crime-stories-with-nancy-grace/',
    whyListen: 'Best for listeners who want a legal and prosecutorial perspective. Nancy Grace brings courtroom experience and strong opinions on the investigation failures.',
    strength: 'Strong legal context and criticism of how the case was handled. Good for understanding why no charges were ever filed.',
    watchOut: 'Opinionated and prosecutorial in tone. Not neutral. Nancy Grace has strong views on suspects that she states as near-fact.',
    listenerFit: ['BestLegalBreakdown', 'BestUpdate'],
    coverageStyle: ['HostCommentary', 'Investigative'],
    sources: ['NewsClips'],
    warnings: ['ChildVictim', 'RevealsOutcomeEarly'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
    spoilerInDescription: true,
  },
  {
    podcastName: 'Zone 7 with Sheryl McCollum',
    episodeTitle: 'JonBenét Ramsey: A Cold Case Expert Weighs In',
    episodeId: 'zone7-jonbenet',
    durationFormatted: '37 min',
    releaseDate: 'January 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/zone-7-with-sheryl-mccollum/',
    spotifyUrl: 'https://open.spotify.com/show/zone7',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/zone-7/',
    whyListen: 'Best for listeners who want a cold case investigator\'s perspective. Sheryl McCollum is a working cold case detective — her analysis is grounded in real investigative experience.',
    strength: 'Most credible investigative voice. Covers what a modern investigation would look like and what evidence still matters.',
    watchOut: 'Assumes familiarity with the basic case facts. Better as a follow-up than a first listen.',
    listenerFit: ['BestLocalContext', 'ForExperiencedListeners', 'BetterAsFollowUp'],
    coverageStyle: ['Investigative', 'InterviewBased'],
    sources: ['DetectiveInterview', 'PoliceRecords'],
    warnings: ['ChildVictim'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
];

// ── Laci Peterson ─────────────────────────────────────────────

export const LACI_PETERSON_EPISODE_CARDS: PodcastEpisodeCard[] = [
  {
    podcastName: 'RedHanded',
    episodeTitle: 'Scott Peterson: Sex, Lies & Fishing Boats (Parts 1 & 2)',
    episodeId: 'redhanded-laci',
    durationFormatted: '195 min',
    releaseDate: 'March 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/redhanded/',
    spotifyUrl: 'https://open.spotify.com/show/redhanded',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/redhanded/',
    whyListen: 'Best deep dive on the Laci Peterson case. Two-part series covers the full story — the marriage, the affair, the investigation, and the trial — with sharp feminist analysis and no filler.',
    strength: 'Most thorough coverage available. Includes strong victim-centered framing and does not let Scott Peterson\'s narrative dominate. Best for listeners who want the full picture.',
    watchOut: 'Long. At 195 minutes combined, this is a commitment. Split across two sessions if needed.',
    listenerFit: ['BestDeepDive', 'BestVictimBackground', 'BestTimeline'],
    coverageStyle: ['Narrative', 'Investigative'],
    sources: ['NewsClips', 'PoliceRecords'],
    warnings: ['IntimatePartnerViolence', 'HeavyEmotionalContent'],
    hostType: 'FemaleDuo',
    banterLevel: 'Low',
  },
  {
    podcastName: 'Mile Higher',
    episodeTitle: 'The Murder of Laci Peterson: Scott Peterson\'s Death Sentence Overturned',
    episodeId: 'milehigher-laci',
    durationFormatted: '108 min',
    releaseDate: 'September 2022',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/mile-higher/',
    spotifyUrl: 'https://open.spotify.com/show/mile-higher',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/mile-higher/',
    whyListen: 'Best for listeners who want the most recent legal update. Covers the 2021 death sentence reversal and what it means for the case going forward.',
    strength: 'Most current legal coverage. Explains the appeals process and the Innocence Project involvement in plain language.',
    watchOut: 'Conversational style with some host banter. Not as forensically detailed as RedHanded. Reveals legal outcome early in the episode.',
    listenerFit: ['BestUpdate', 'BestLegalBreakdown'],
    coverageStyle: ['Conversational', 'Narrative'],
    sources: ['NewsClips'],
    warnings: ['RevealsOutcomeEarly', 'IntimatePartnerViolence'],
    hostType: 'FemaleDuo',
    banterLevel: 'Medium',
    spoilerInTitle: true,
  },
  {
    podcastName: 'Truth & Justice with Bob Ruff',
    episodeTitle: 'Murder of Laci Peterson with Dr. Scott',
    episodeId: 'truthjustice-laci',
    durationFormatted: '71 min',
    releaseDate: 'August 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/truth-justice-with-bob-ruff/',
    spotifyUrl: 'https://open.spotify.com/show/truth-justice',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/truth-justice/',
    whyListen: 'Best for listeners who want to understand the wrongful conviction argument. Bob Ruff has covered wrongful convictions for years and brings a skeptical eye to the prosecution\'s case.',
    strength: 'Only major podcast that takes the wrongful conviction claim seriously and examines it rigorously. Includes expert interview.',
    watchOut: 'Advocates for a specific position. If you want neutral coverage, this is not it. Assumes you already know the basic case facts.',
    listenerFit: ['BestLegalBreakdown', 'ForExperiencedListeners', 'BetterAsFollowUp'],
    coverageStyle: ['Investigative', 'InterviewBased'],
    sources: ['DetectiveInterview', 'PoliceRecords'],
    warnings: ['IntimatePartnerViolence', 'DescriptionContainsSpoilers'],
    hostType: 'SoloMale',
    banterLevel: 'Low',
  },
  {
    podcastName: 'LOVE MURDER',
    episodeTitle: 'America\'s Brown-Eyed Girl: The Case of Laci and Scott Peterson',
    episodeId: 'lovemurder-laci',
    durationFormatted: '120 min',
    releaseDate: 'February 2023',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/love-murder/',
    spotifyUrl: 'https://open.spotify.com/show/love-murder',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/love-murder/',
    whyListen: 'Best for listeners who want a victim-centered, emotionally resonant version. Focuses on who Laci Peterson was as a person, not just as a victim.',
    strength: 'Strongest victim background of any coverage. Spends real time on Laci\'s life, personality, and relationships before the crime.',
    watchOut: 'More emotional and narrative-driven than analytical. Not the best choice if you want forensic or legal detail.',
    listenerFit: ['BestVictimBackground', 'BestFirstListen'],
    coverageStyle: ['Narrative', 'Documentary'],
    sources: ['FamilyInterview', 'NewsClips'],
    warnings: ['IntimatePartnerViolence', 'HeavyEmotionalContent'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
];

// ── Gabby Petito ──────────────────────────────────────────────

export const GABBY_PETITO_EPISODE_CARDS: PodcastEpisodeCard[] = [
  {
    podcastName: 'True Crime Brewery',
    episodeTitle: 'The Case of Gabby Petito',
    episodeId: 'tcbrewery-gabby',
    durationFormatted: '82 min',
    releaseDate: 'October 2021',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/true-crime-brewery/',
    spotifyUrl: 'https://open.spotify.com/show/true-crime-brewery',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/true-crime-brewery/',
    whyListen: 'Best first listen for the Gabby Petito case. Calm, methodical coverage of the timeline, the van life trip, and the investigation without the media circus framing.',
    strength: 'Best timeline clarity. Covers the full sequence of events — the road trip, the 911 call, the disappearance, and the search — in a clear, non-sensational way.',
    watchOut: 'Recorded in 2021 before the full investigation concluded. Does not include the Brian Laundrie notebook confession or the civil lawsuit.',
    listenerFit: ['BestFirstListen', 'BestTimeline'],
    coverageStyle: ['Narrative', 'Conversational'],
    sources: ['NewsClips'],
    warnings: ['IntimatePartnerViolence', 'DomesticViolence'],
    hostType: 'MixedDuo',
    banterLevel: 'Medium',
  },
  {
    podcastName: 'What Came Next',
    episodeTitle: 'Nichole Schmidt — Netflix\'s American Murder: Gabby Petito',
    episodeId: 'whatcamenext-gabby',
    durationFormatted: '44 min',
    releaseDate: 'February 2025',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/what-came-next/',
    spotifyUrl: 'https://open.spotify.com/show/what-came-next',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/what-came-next/',
    whyListen: 'Best for listeners who want to hear directly from Gabby\'s mother. Nichole Schmidt speaks about the case, the Netflix documentary, and what she wants people to understand about her daughter.',
    strength: 'Only major podcast with a direct family interview. Gabby\'s mother speaks about the case in her own words — this is primary source material.',
    watchOut: 'Emotionally heavy. Nichole Schmidt discusses grief, the media attention, and the civil lawsuit. Not for listeners in a vulnerable headspace.',
    listenerFit: ['BestFamilyPerspective', 'BestVictimBackground'],
    coverageStyle: ['InterviewBased'],
    sources: ['FamilyInterview'],
    warnings: ['HeavyEmotionalContent', 'IntimatePartnerViolence', 'DomesticViolence'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
  {
    podcastName: 'Crime Writers On',
    episodeTitle: 'American Murder: Gabby Petito',
    episodeId: 'crimewriters-gabby',
    durationFormatted: '53 min',
    releaseDate: 'February 2025',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-writers-on/',
    spotifyUrl: 'https://open.spotify.com/show/crime-writers-on',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/crime-writers-on/',
    whyListen: 'Best companion listen after watching the Netflix documentary. Crime writers break down what the documentary got right, what it left out, and how the media coverage shaped public perception.',
    strength: 'Best media criticism and documentary analysis. Covers the "missing white woman syndrome" angle thoughtfully without dismissing Gabby\'s case.',
    watchOut: 'Assumes you have watched the Netflix documentary. Not a standalone case overview.',
    listenerFit: ['BetterAsFollowUp', 'ForExperiencedListeners'],
    coverageStyle: ['HostCommentary', 'Investigative'],
    sources: ['NewsClips'],
    warnings: ['IntimatePartnerViolence', 'DomesticViolence'],
    hostType: 'FemaleDuo',
    banterLevel: 'Low',
  },
  {
    podcastName: 'Crime Analyst',
    episodeTitle: 'The Murder of Gabby Petito — Remastered Series',
    episodeId: 'crimeanalyst-gabby',
    durationFormatted: '67 min',
    releaseDate: 'March 2024',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-analyst/',
    spotifyUrl: 'https://open.spotify.com/show/crime-analyst',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/crime-analyst/',
    whyListen: 'Best for listeners who want the most detailed analytical breakdown. Remastered with updated information including the Brian Laundrie notebook and civil lawsuit outcome.',
    strength: 'Most current and complete coverage. Includes the notebook confession, the civil lawsuit, and what the evidence tells us about the final days.',
    watchOut: 'Dense. This is the most detail-heavy version available. Better as a deep dive than a first listen.',
    listenerFit: ['BestDeepDive', 'BestEvidenceBreakdown', 'BestUpdate'],
    coverageStyle: ['Investigative', 'EvidenceFocused'],
    sources: ['PoliceRecords', 'NewsClips'],
    warnings: ['IntimatePartnerViolence', 'DomesticViolence', 'RevealsOutcomeEarly'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
  },
];

// ── Delphi Murders ────────────────────────────────────────────

export const DELPHI_EPISODE_CARDS: PodcastEpisodeCard[] = [
  {
    podcastName: 'Delphi Murders: Richard Allen & The Search For The Truth',
    episodeTitle: 'Trial Day 12 Recap: The Prosecution\'s Case',
    episodeId: 'delphi-dedicated-trial',
    durationFormatted: '21 min',
    releaseDate: 'November 2024',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/delphi-murders/',
    spotifyUrl: 'https://open.spotify.com/show/delphi-murders',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/delphi-murders/',
    whyListen: 'Best for listeners who want to follow the Richard Allen trial in real time. This dedicated show has covered the case since 2017 and provides daily trial recaps.',
    strength: 'Deepest case-specific coverage available. The host has followed this case for seven years and knows every detail. Best local context of any podcast.',
    watchOut: 'Assumes significant familiarity with the case. Not a good starting point. Best after you have listened to a case overview first.',
    listenerFit: ['BestLocalContext', 'BestUpdate', 'ForExperiencedListeners'],
    coverageStyle: ['Investigative', 'LocalReporting', 'CourtFocused'],
    sources: ['CourtAudio', 'LocalReporting', 'PoliceRecords'],
    warnings: ['ChildVictim', 'DescriptionContainsSpoilers'],
    hostType: 'SoloFemale',
    banterLevel: 'Low',
    spoilerInDescription: true,
  },
  {
    podcastName: 'Hidden Killers with Tony Brueski',
    episodeTitle: 'Delphi Murders Trial Begins: Prosecutors Say Richard Allen Forced Girls Down the Hill',
    episodeId: 'hiddenkillers-delphi',
    durationFormatted: '21 min',
    releaseDate: 'October 2024',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/hidden-killers/',
    spotifyUrl: 'https://open.spotify.com/show/hidden-killers',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/hidden-killers/',
    whyListen: 'Best short update on the trial opening. Covers the prosecution\'s opening statement and what the key arguments are without requiring deep prior knowledge.',
    strength: 'Good quick orientation to where the trial stands. Clear and accessible for listeners who are not following the case daily.',
    watchOut: 'Short and news-focused. Does not provide case background. Pair with a case overview episode first.',
    listenerFit: ['BestShortOverview', 'BestUpdate'],
    coverageStyle: ['Narrative', 'TimelineFocused'],
    sources: ['NewsClips', 'CourtAudio'],
    warnings: ['ChildVictim', 'TitleContainsSpoilers'],
    hostType: 'SoloMale',
    banterLevel: 'Low',
    spoilerInTitle: true,
  },
  {
    podcastName: 'FBI Unscripted',
    episodeTitle: 'Delphi Murders: Judge Rejects Defense\'s Cult Killing Theory',
    episodeId: 'fbiunscripted-delphi',
    durationFormatted: '9 min',
    releaseDate: 'October 2024',
    applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/fbi-unscripted/',
    spotifyUrl: 'https://open.spotify.com/show/fbi-unscripted',
    listenNotesUrl: 'https://www.listennotes.com/podcasts/fbi-unscripted/',
    whyListen: 'Best for listeners who want a former FBI perspective on the defense strategy. Short and focused on the legal and investigative implications of the cult theory ruling.',
    strength: 'Unique FBI lens on the case. Explains what the defense\'s cult theory was and why the judge rejected it in plain language.',
    watchOut: 'Very short. Covers one specific legal development only. Not a case overview.',
    listenerFit: ['BestLegalBreakdown', 'BestUpdate'],
    coverageStyle: ['Investigative', 'InterviewBased'],
    sources: ['DetectiveInterview'],
    warnings: ['ChildVictim'],
    hostType: 'SoloMale',
    banterLevel: 'Low',
  },
];

// ── Full case objects ─────────────────────────────────────────

export const FEATURED_CASES: Partial<TruecrimeCase>[] = [
  {
    id: 'case_idaho4',
    title: 'The Idaho 4 Murders',
    year: 2022,
    location: 'Moscow, Idaho',
    primaryCategory: 'Murdered',
    caseStatus: 'TrialPending',
    era: 'Recent',
    summary:
      'In November 2022, four University of Idaho students — Kaylee Goncalves, Madison Mogen, Xana Kernodle, and Ethan Chapin — were found stabbed to death in an off-campus house in Moscow, Idaho. The case drew national attention for the weeks-long gap between the murders and the arrest of a suspect, and for the role social media played in the investigation. A suspect has been charged and is awaiting trial, but significant questions about the evidence remain contested.',
    recentDevelopments: true,
    lastDevelopmentDate: '2024-11',
    crimeTypes: ['Homicide'],
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['MediaCircus', 'KeepsYouGuessing'],
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    tags: ['College Students', 'Cold Case', 'Recent', 'Trial Pending'],
    coverageHighlights: ['BestFirstListenAvailable', 'DeepDiveAvailable', 'CourtCoverageAvailable', 'RecentUpdateAvailable'],
    episodeCards: IDAHO4_EPISODE_CARDS,
    podcasts: [],
  },
  {
    id: 'case_jonbenet',
    title: 'JonBenét Ramsey',
    year: 1996,
    location: 'Boulder, Colorado',
    primaryCategory: 'Murdered',
    caseStatus: 'ColdCase',
    era: '1990s',
    summary:
      'In December 1996, six-year-old JonBenét Ramsey was found murdered in the basement of her family\'s home in Boulder, Colorado, hours after her parents reported her missing on Christmas morning. The case became one of the most scrutinized unsolved murders in American history, marked by a controversial investigation, a ransom note found in the home, and decades of competing theories about who was responsible. No one has ever been charged.',
    recentDevelopments: false,
    crimeTypes: ['Homicide'],
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['MediaCircus', 'KeepsYouGuessing', 'ColdCaseRevived'],
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1548407260-da850faa41e3?w=800',
    tags: ['Cold Case', 'Unsolved', '1990s', 'Child Victim'],
    coverageHighlights: ['BestFirstListenAvailable', 'DeepDiveAvailable', 'DeepDiveAvailable'],
    episodeCards: JONBENET_EPISODE_CARDS,
    podcasts: [],
  },
  {
    id: 'case_laci_peterson',
    title: 'Laci Peterson',
    year: 2002,
    location: 'Modesto, California',
    primaryCategory: 'Murdered',
    caseStatus: 'Conviction',
    era: '2000s',
    summary:
      'In December 2002, Laci Peterson disappeared from her home in Modesto, California, eight months pregnant with her first child. Her remains and those of her unborn son were discovered in San Francisco Bay four months later. The case became a defining true crime story of the early 2000s, raising questions about intimate partner violence, media coverage of missing women, and the reliability of the evidence used to secure a conviction. A wrongful conviction claim has since been filed.',
    recentDevelopments: true,
    lastDevelopmentDate: '2023-06',
    crimeTypes: ['Homicide'],
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    tags: ['Intimate Partner Violence', 'Conviction', '2000s', 'Wrongful Conviction Claim'],
    coverageHighlights: ['BestFirstListenAvailable', 'DeepDiveAvailable', 'FamilyInterviewAvailable', 'RecentUpdateAvailable', 'CourtCoverageAvailable'],
    episodeCards: LACI_PETERSON_EPISODE_CARDS,
    podcasts: [],
  },
  {
    id: 'case_gabby_petito',
    title: 'Gabby Petito',
    year: 2021,
    location: 'Teton County, Wyoming',
    primaryCategory: 'Murdered',
    caseStatus: 'Solved',
    era: 'Recent',
    summary:
      'In September 2021, 22-year-old Gabby Petito was reported missing after a cross-country van trip with her fiancé Brian Laundrie. Her remains were found in Grand Teton National Park weeks later. The case sparked a national conversation about domestic violence, the "missing white woman syndrome" in media coverage, and the role of social media in criminal investigations. A notebook found with Brian Laundrie\'s remains contained what investigators described as a confession.',
    recentDevelopments: true,
    lastDevelopmentDate: '2025-02',
    crimeTypes: ['Homicide'],
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    tags: ['Domestic Violence', 'Recent', 'Social Media', 'Family Interview Available'],
    coverageHighlights: ['BestFirstListenAvailable', 'DeepDiveAvailable', 'FamilyInterviewAvailable', 'PrimarySourcesAvailable', 'RecentUpdateAvailable'],
    episodeCards: GABBY_PETITO_EPISODE_CARDS,
    podcasts: [],
  },
  {
    id: 'case_delphi_murders',
    title: 'The Delphi Murders',
    year: 2017,
    location: 'Delphi, Indiana',
    primaryCategory: 'Murdered',
    caseStatus: 'TrialPending',
    era: '2010s',
    summary:
      'In February 2017, 13-year-old Abby Williams and 14-year-old Libby Koch were found murdered near a hiking trail in Delphi, Indiana, a day after they were last seen on the Monon High Bridge Trail. Libby had captured audio and video of a man on the trail on her phone, which investigators released publicly in hopes of identifying him. The case went unsolved for five years before a local man was arrested in 2022. His trial has been marked by unusual legal arguments and ongoing controversy.',
    recentDevelopments: true,
    lastDevelopmentDate: '2024-11',
    crimeTypes: ['Homicide'],
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['KeepsYouGuessing', 'ColdCaseRevived', 'MediaCircus'],
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    tags: ['Child Victims', 'Cold Case', 'Trial Pending', 'Primary Audio Evidence'],
    coverageHighlights: ['DeepDiveAvailable', 'LocalReportingAvailable', 'CourtCoverageAvailable', 'RecentUpdateAvailable'],
    episodeCards: DELPHI_EPISODE_CARDS,
    podcasts: [],
  },
];
