import type { TruecrimeCase, VibeCategory } from './types';

// ============================================================
// Mock Dataset: 26 True Crime Cases
// ============================================================

export const MOCK_CASES: TruecrimeCase[] = [
  {
    id: 'case_001',
    title: 'The Golden State Killer',
    summary:
      'A decades-long investigation into a serial offender who terrorized California in the 1970s and 80s, ultimately identified through genealogical DNA evidence in 2018.',
    tags: ['Cold Case', 'DNA Evidence', 'Serial Offender', 'California'],
    caseStatus: 'Solved',
    crimeTypes: ['SerialOffender', 'Homicide'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ColdCaseRevived', 'ShockingTurns', 'RedHerrings'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    hostName: 'Paul Holes & Billy Jensen',
    whyWeLoveIt: "The genealogical DNA breakthrough that cracked this case is one of the most gripping detective stories ever told.",
    perfectFor: ['Late night listening', 'Cold case obsessives', 'True crime veterans'],
    contentNotes: ['Sexual assault content', 'Detailed crime scenes', 'Decades of investigation'],
    podcasts: [
      {
        podcastName: 'My Favorite Murder',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/my-favorite-murder/id1074507850',
        spotifyUrl: 'https://open.spotify.com/show/0U6kBpBFHJFqFIgAMmPnJA',
        episodeCount: 3,
        coverageDepth: 'Overview',
        timeCommitment: 'Under1Hr',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Mar 2018',
        startHereNote: 'Start with the episode released after the 2018 arrest.',
        hostType: 'FemaleDuo',
        banterLevel: 'High',
        primarySources: [],
      },
      {
        podcastName: 'Your Own Backyard',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/your-own-backyard/id1474742975',
        spotifyUrl: 'https://open.spotify.com/show/1iohmBNlRooIVtukKeavRa',
        episodeCount: 8,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Jun 2024',
        startHereNote: 'Begin at Episode 1 for full chronological context.',
        hostType: 'SoloMale',
        banterLevel: 'Low',
        primarySources: ['FamilyInterview', 'DetectiveInterview'],
      },
    ],
  },
  {
    id: 'case_002',
    title: 'The Disappearance of Maura Murray',
    summary:
      'A 21-year-old college student vanished after a car accident on a rural New Hampshire road in 2004, leaving behind a mystery that investigators and amateur sleuths have pursued for over two decades.',
    tags: ['Missing Person', 'Unsolved', 'New Hampshire', 'College Student'],
    caseStatus: 'Unsolved',
    crimeTypes: ['MissingPerson'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    hostName: 'Lance Reish',
    whyWeLoveIt: "Two decades of amateur sleuthing, dead ends, and haunting unanswered questions make this one of the most compelling missing persons cases.",
    perfectFor: ['Commute', 'Unsolved mystery fans', 'Long drives'],
    contentNotes: ['Unsolved case', 'Speculation heavy', 'No graphic content'],
    podcasts: [
      {
        podcastName: 'Your Own Backyard',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/your-own-backyard/id1474742975',
        spotifyUrl: 'https://open.spotify.com/show/1iohmBNlRooIVtukKeavRa',
        episodeCount: 12,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Dec 2024',
        startHereNote: 'Start from the beginning; each episode builds on the last.',
      },
      {
        podcastName: 'Casefile True Crime',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017',
        spotifyUrl: 'https://open.spotify.com/show/4wDcyMnSqKHQAMpBJFCBaS',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Aug 2021',
        startHereNote: 'A solid two-part overview for newcomers to the case.',
      },
    ],
  },
  {
    id: 'case_003',
    title: 'The Murder of Laci Peterson',
    summary:
      'A pregnant woman went missing on Christmas Eve 2002 in Modesto, California. The investigation that followed revealed a shocking double life and led to a high-profile murder trial.',
    tags: ['Homicide', 'California', 'Trial', 'Media Coverage'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'MediaCircus'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A wrongful conviction story that exposes systemic failures in the justice system with meticulous, unflinching reporting.",
    perfectFor: ['Justice seekers', 'Legal drama fans', 'Commute'],
    contentNotes: ['Wrongful conviction themes', 'Courtroom focused', 'Minimal graphic content'],
    podcasts: [
      {
        podcastName: 'Dateline NBC',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/dateline-nbc/id1464919521',
        spotifyUrl: 'https://open.spotify.com/show/3IM0HgeLB0GULBLqVTmBMb',
        episodeCount: 4,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Nov 2020',
        startHereNote: 'The four-part series provides thorough trial coverage.',
      },
    ],
  },
  {
    id: 'case_004',
    title: 'The Zodiac Killer',
    summary:
      'An unidentified serial killer who operated in Northern California in the late 1960s and early 1970s, taunting police and media with cryptic letters and ciphers, several of which remain unsolved.',
    tags: ['Serial Killer', 'Unsolved', 'Ciphers', 'California', 'Cold Case'],
    caseStatus: 'Unsolved',
    crimeTypes: ['SerialOffender', 'Homicide'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings', 'ShockingTurns'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Aug 2022',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cult that operated in plain sight for decades, with survivor testimony that is both devastating and empowering.",
    perfectFor: ['Psychology fans', 'Cult obsessives', 'Wind down'],
    contentNotes: ['Psychological manipulation', 'Survivor stories', 'Some graphic content'],
    podcasts: [
      {
        podcastName: 'Casefile True Crime',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017',
        spotifyUrl: 'https://open.spotify.com/show/4wDcyMnSqKHQAMpBJFCBaS',
        episodeCount: 3,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jan 2020',
        startHereNote: 'Three-part series covers the known victims and cipher history.',
      },
    ],
  },
  {
    id: 'case_005',
    title: 'The JonBenét Ramsey Case',
    summary:
      'The 1996 murder of a six-year-old beauty pageant contestant in Boulder, Colorado, remains one of the most scrutinized and debated unsolved cases in American history.',
    tags: ['Unsolved', 'Colorado', 'Cold Case', 'Child Victim'],
    caseStatus: 'Unsolved',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings', 'MediaCircus'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Oct 2023',
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "The most audacious financial fraud in American history, told through the voices of those who lost everything.",
    perfectFor: ['Finance fans', 'Fraud obsessives', 'Commute'],
    contentNotes: ['Financial crime focus', 'No graphic violence', 'Complex legal themes'],
    podcasts: [
      {
        podcastName: 'The Deck',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-deck/id1551429357',
        spotifyUrl: 'https://open.spotify.com/show/3IM0HgeLB0GULBTmBMb',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Nov 2023',
        startHereNote: 'Start from Episode 1 for full background on the family and investigation.',
      },
    ],
  },
  {
    id: 'case_006',
    title: 'The West Memphis Three',
    summary:
      'Three teenagers were convicted of the 1993 murders of three young boys in West Memphis, Arkansas. After nearly two decades in prison, new evidence and public advocacy led to their release, but the true killer was never identified.',
    tags: ['Wrongful Conviction', 'Arkansas', 'Advocacy', 'Teens'],
    caseStatus: 'WrongfulConviction',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['WrongfulConviction', 'ShockingTurns', 'MediaCircus'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A small-town disappearance that unraveled an entire community, told with extraordinary empathy for the victim.",
    perfectFor: ['Small town stories', 'Missing persons fans', 'Late night'],
    contentNotes: ['Missing person', 'Community impact', 'Some speculation'],
    podcasts: [
      {
        podcastName: 'Wrongful Conviction',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/wrongful-conviction/id1234567890',
        spotifyUrl: 'https://open.spotify.com/show/wrongfulconviction',
        episodeCount: 5,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Feb 2019',
        startHereNote: 'The interview-based format gives voice to those directly involved.',
      },
    ],
  },
  {
    id: 'case_007',
    title: 'The Watts Family Murders',
    summary:
      'In August 2018, Chris Watts murdered his pregnant wife and two young daughters in Frederick, Colorado. The case shocked the country and raised questions about domestic violence warning signs.',
    tags: ['Homicide', 'Colorado', 'Domestic Violence', 'Family'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: true,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A decades-long mystery that proves some cases never truly go cold, with new DNA evidence still emerging.",
    perfectFor: ['Cold case fans', 'Long commutes', 'Curious minds'],
    contentNotes: ['Cold case', 'DNA evidence focus', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Sep 2018',
        startHereNote: 'A focused two-episode overview of the case and investigation.',
      },
    ],
  },
  {
    id: 'case_008',
    title: 'The Disappearance of Gabby Petito',
    summary:
      'A 22-year-old travel blogger went missing during a cross-country road trip in 2021. The case drew massive public attention and raised important conversations about missing persons coverage disparities.',
    tags: ['Missing Person', 'Wyoming', 'Social Media', 'Recent'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide', 'MissingPerson'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A chilling look at how a predator operated in plain sight, and the survivors who finally brought him to justice.",
    perfectFor: ['Survivor stories', 'Justice seekers', 'Commute'],
    contentNotes: ['Sexual assault themes', 'Survivor testimony', 'Graphic at times'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 3,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Nov 2021',
        startHereNote: 'Three episodes covering the disappearance, search, and aftermath.',
      },
    ],
  },
  {
    id: 'case_009',
    title: 'The Menendez Brothers',
    summary:
      'In 1989, brothers Erik and Lyle Menendez shot and killed their wealthy parents in their Beverly Hills home. The subsequent trials became a defining media spectacle of the 1990s.',
    tags: ['Homicide', 'Beverly Hills', 'Trial', 'Media Coverage'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'MediaCircus', 'NarrativeShifts'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Mar 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "The intersection of celebrity, obsession, and violence explored with nuance and sensitivity.",
    perfectFor: ['Pop culture fans', 'Psychology buffs', 'Wind down'],
    contentNotes: ['Celebrity case', 'Stalking themes', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Dateline NBC',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/dateline-nbc/id1464919521',
        spotifyUrl: 'https://open.spotify.com/show/3IM0HgeLB0GULBLqVTmBMb',
        episodeCount: 3,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Apr 2025',
        startHereNote: 'Recent episodes cover the 2025 resentencing developments.',
      },
    ],
  },
  {
    id: 'case_010',
    title: 'The O.J. Simpson Trial',
    summary:
      'The 1994 murders of Nicole Brown Simpson and Ron Goldman, and the subsequent "Trial of the Century," reshaped American views on race, celebrity, and the justice system.',
    tags: ['Trial', 'Los Angeles', 'Media Coverage', 'Race', 'Celebrity'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A masterclass in how charisma and manipulation can blind even the most intelligent people.",
    perfectFor: ['Psychology fans', 'Cult obsessives', 'Late night'],
    contentNotes: ['Psychological manipulation', 'Cult dynamics', 'Some disturbing content'],
    podcasts: [
      {
        podcastName: 'American Scandal',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/american-scandal/id1474672641',
        spotifyUrl: 'https://open.spotify.com/show/americanscandal',
        episodeCount: 8,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Dec 2021',
        startHereNote: 'Eight-part series provides deep historical and cultural context.',
      },
    ],
  },
  {
    id: 'case_011',
    title: 'The Delphi Murders',
    summary:
      'Two teenage girls were murdered on a hiking trail in Delphi, Indiana in February 2017. A suspect was arrested in 2022 and the trial began in 2024, bringing new attention to the case.',
    tags: ['Homicide', 'Indiana', 'Teens', 'Recent Developments'],
    caseStatus: 'Ongoing',
    crimeTypes: ['Homicide'],
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'ColdCaseRevived'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Oct 2024',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A wrongful conviction that took decades to overturn, with advocacy journalism at its finest.",
    perfectFor: ['Justice seekers', 'Legal drama fans', 'Commute'],
    contentNotes: ['Wrongful conviction', 'Courtroom focus', 'Minimal graphic content'],
    podcasts: [
      {
        podcastName: 'Down the Hill: The Delphi Murders',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/down-the-hill/id1450686031',
        spotifyUrl: 'https://open.spotify.com/show/downthehill',
        episodeCount: 10,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Nov 2024',
        startHereNote: 'The definitive podcast on this case. Start from Episode 1.',
      },
    ],
  },
  {
    id: 'case_012',
    title: 'Elizabeth Holmes and Theranos',
    summary:
      'The rise and fall of Silicon Valley startup Theranos and its founder Elizabeth Holmes, who defrauded investors and endangered patients with a fraudulent blood-testing technology.',
    tags: ['Fraud', 'Silicon Valley', 'Corporate Crime', 'Female Perpetrator'],
    caseStatus: 'Solved',
    crimeTypes: ['Fraud', 'Corruption'],
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A financial scandal that exposed the dark side of Silicon Valley ambition and the cost of unchecked fraud.",
    perfectFor: ['Finance fans', 'Tech culture', 'Commute'],
    contentNotes: ['Financial fraud', 'No graphic violence', 'Complex themes'],
    podcasts: [
      {
        podcastName: 'The Dropout',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-dropout/id1449500734',
        spotifyUrl: 'https://open.spotify.com/show/thedropout',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Mar 2019',
        startHereNote: 'Six-part investigative series from ABC News. Start at Episode 1.',
      },
    ],
  },
  {
    id: 'case_013',
    title: 'The Murder of Ahmaud Arbery',
    summary:
      'A 25-year-old Black man was pursued and shot while jogging in a Georgia neighborhood in February 2020. The case sparked national outrage and a federal hate crime conviction.',
    tags: ['Homicide', 'Georgia', 'Racial Justice', 'Recent'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "The investigation that changed how law enforcement approaches serial cases, told with gripping procedural detail.",
    perfectFor: ['Procedural fans', 'Cold case obsessives', 'Long drives'],
    contentNotes: ['Serial offender', 'Graphic at times', 'Investigative focus'],
    podcasts: [
      {
        podcastName: 'Casefile True Crime',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017',
        spotifyUrl: 'https://open.spotify.com/show/4wDcyMnSqKHQAMpBJFCBaS',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Feb 2022',
        startHereNote: 'Two-part coverage of the crime and trial.',
      },
    ],
  },
  {
    id: 'case_014',
    title: 'The Manson Family Murders',
    summary:
      'In the summer of 1969, members of Charles Manson\'s cult carried out a series of brutal murders in Los Angeles, including the killing of actress Sharon Tate, sending shockwaves through American culture.',
    tags: ['Cult', 'Los Angeles', 'Serial Murders', '1960s'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide', 'Cult'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ShockingTurns', 'MediaCircus', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A gripping look at how a predator used the internet to target victims, and the digital trail that caught him.",
    perfectFor: ['Tech crime fans', 'Procedural fans', 'Commute'],
    contentNotes: ['Online predator', 'Some graphic content', 'Digital investigation'],
    podcasts: [
      {
        podcastName: 'American Scandal',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/american-scandal/id1474672641',
        spotifyUrl: 'https://open.spotify.com/show/americanscandal',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jun 2022',
        startHereNote: 'Six episodes covering the cult, the crimes, and the cultural aftermath.',
      },
    ],
  },
  {
    id: 'case_015',
    title: 'The Kidnapping of Elizabeth Smart',
    summary:
      'In June 2002, 14-year-old Elizabeth Smart was abducted from her Salt Lake City home and held captive for nine months. Her rescue and subsequent advocacy work have made her a prominent voice for survivors.',
    tags: ['Kidnapping', 'Utah', 'Survivor', 'Advocacy'],
    caseStatus: 'Solved',
    crimeTypes: ['Kidnapping'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cold case that was cracked by a community of amateur investigators, proving the power of collective memory.",
    perfectFor: ['Cold case fans', 'Community stories', 'Wind down'],
    contentNotes: ['Cold case', 'Community involvement', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'May 2019',
        startHereNote: 'Respectful, survivor-centered coverage of the case.',
      },
    ],
  },
  {
    id: 'case_016',
    title: 'The Disappearance of DB Cooper',
    summary:
      'In November 1971, a man using the alias D.B. Cooper hijacked a Northwest Orient flight, extorted $200,000 in ransom, and parachuted into the Pacific Northwest, never to be identified.',
    tags: ['Hijacking', 'Unsolved', 'Pacific Northwest', 'Cold Case'],
    caseStatus: 'Unsolved',
    crimeTypes: ['Fraud'],
    era: 'Pre1990',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A Ponzi scheme that devastated thousands of families, told through the voices of those who lost everything.",
    perfectFor: ['Finance fans', 'Fraud obsessives', 'Commute'],
    contentNotes: ['Financial crime', 'No graphic violence', 'Victim focused'],
    podcasts: [
      {
        podcastName: 'Casefile True Crime',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017',
        spotifyUrl: 'https://open.spotify.com/show/4wDcyMnSqKHQAMpBJFCBaS',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Nov 2021',
        startHereNote: 'Two-part episode covers the hijacking and the decades of investigation.',
      },
    ],
  },
  {
    id: 'case_017',
    title: 'The Murdaugh Family Murders',
    summary:
      'In June 2021, prominent South Carolina attorney Alex Murdaugh\'s wife and son were found shot dead on the family estate. The investigation exposed a web of financial fraud, addiction, and family secrets spanning decades.',
    tags: ['Homicide', 'South Carolina', 'Legal Drama', 'Family Secrets'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide', 'Fraud'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'NarrativeShifts', 'MediaCircus'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Jan 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A missing person case that exposed a pattern of violence against women in a small community.",
    perfectFor: ['Missing persons fans', 'Justice seekers', 'Late night'],
    contentNotes: ['Missing person', 'Violence against women', 'Some graphic content'],
    podcasts: [
      {
        podcastName: 'Murdaugh Murders: A Southern Scandal',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/murdaugh-murders/id1600000000',
        spotifyUrl: 'https://open.spotify.com/show/murdaughmurders',
        episodeCount: 14,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Feb 2025',
        startHereNote: 'The definitive podcast on this case. Begin at Episode 1.',
      },
    ],
  },
  {
    id: 'case_018',
    title: 'The Night Stalker',
    summary:
      'Richard Ramirez terrorized Los Angeles and San Francisco in 1984 and 1985, committing a series of home invasions, murders, and sexual assaults before being identified and captured.',
    tags: ['Serial Killer', 'California', 'Home Invasion', '1980s'],
    caseStatus: 'Solved',
    crimeTypes: ['SerialOffender', 'Homicide'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ShockingTurns', 'ColdCaseRevived'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1510784722466-f2aa240a3b2b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cult that promised enlightenment and delivered exploitation, with survivor stories that are both harrowing and hopeful.",
    perfectFor: ['Cult obsessives', 'Psychology fans', 'Long drives'],
    contentNotes: ['Cult dynamics', 'Psychological manipulation', 'Survivor testimony'],
    podcasts: [
      {
        podcastName: 'My Favorite Murder',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/my-favorite-murder/id1074507850',
        spotifyUrl: 'https://open.spotify.com/show/0U6kBpBFHJFqFIgAMmPnJA',
        episodeCount: 2,
        coverageDepth: 'Overview',
        timeCommitment: 'Under1Hr',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jul 2019',
        startHereNote: 'A conversational overview of the case and capture.',
      },
    ],
  },
  {
    id: 'case_019',
    title: 'The NXIVM Cult',
    summary:
      'NXIVM presented itself as a self-improvement organization but operated as a coercive cult. Its leader Keith Raniere was convicted of sex trafficking and racketeering in 2019.',
    tags: ['Cult', 'New York', 'Sex Trafficking', 'Corporate Crime'],
    caseStatus: 'Solved',
    crimeTypes: ['Cult', 'Corruption'],
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'NarrativeShifts', 'MediaCircus'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1520637836862-4d197d17c93a?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A corruption case that reached the highest levels of government, with investigative journalism at its most courageous.",
    perfectFor: ['Political crime fans', 'Investigative journalism', 'Commute'],
    contentNotes: ['Political corruption', 'No graphic violence', 'Complex legal themes'],
    podcasts: [
      {
        podcastName: 'The Vow Podcast',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-vow/id1500000000',
        spotifyUrl: 'https://open.spotify.com/show/thevow',
        episodeCount: 9,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Oct 2020',
        startHereNote: 'Companion to the HBO documentary, featuring first-person accounts.',
      },
    ],
  },
  {
    id: 'case_020',
    title: 'The Disappearance of Natalee Holloway',
    summary:
      'An 18-year-old Alabama student vanished during a graduation trip to Aruba in 2005. The case became an international media story and remains officially unsolved, though a suspect confessed decades later.',
    tags: ['Missing Person', 'Aruba', 'International', 'Unsolved'],
    caseStatus: 'Unsolved',
    crimeTypes: ['MissingPerson', 'Homicide'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'MediaCircus'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Jun 2023',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A kidnapping case that gripped a nation and changed how missing children are reported in the media.",
    perfectFor: ['Missing persons fans', 'Historical cases', 'Commute'],
    contentNotes: ['Kidnapping', 'Child victim', 'Historical case'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: true,
        coverageEndDate: 'Jul 2023',
        startHereNote: 'Updated episode covers the 2023 confession developments.',
      },
    ],
  },
  {
    id: 'case_021',
    title: 'The BTK Killer',
    summary:
      'Dennis Rader terrorized Wichita, Kansas for over three decades, taunting police with letters signed "BTK" before his arrest in 2005. His capture came through a floppy disk he sent to police.',
    tags: ['Serial Killer', 'Kansas', 'Cold Case', 'Solved'],
    caseStatus: 'Solved',
    crimeTypes: ['SerialOffender', 'Homicide'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['KeepsYouGuessing', 'ShockingTurns', 'ColdCaseRevived'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A serial fraud case that exposed how easily trust can be weaponized, told with dark humor and sharp analysis.",
    perfectFor: ['Fraud fans', 'Psychology buffs', 'Commute'],
    contentNotes: ['Financial fraud', 'Psychological manipulation', 'No graphic violence'],
    podcasts: [
      {
        podcastName: 'Casefile True Crime',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017',
        spotifyUrl: 'https://open.spotify.com/show/4wDcyMnSqKHQAMpBJFCBaS',
        episodeCount: 4,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Mar 2020',
        startHereNote: 'Four-part series covering the crimes chronologically.',
      },
    ],
  },
  {
    id: 'case_022',
    title: 'The Making of a Murderer: Steven Avery',
    summary:
      'Steven Avery was exonerated after 18 years in prison for a crime he did not commit, only to be charged with murder two years later. The case raises profound questions about the justice system.',
    tags: ['Wrongful Conviction', 'Wisconsin', 'Justice System', 'Documentary'],
    caseStatus: 'WrongfulConviction',
    crimeTypes: ['Homicide'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['WrongfulConviction', 'ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Sep 2024',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cold case that was finally solved through the persistence of one detective who never gave up.",
    perfectFor: ['Cold case fans', 'Procedural fans', 'Late night'],
    contentNotes: ['Cold case', 'Homicide', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Wrongful Conviction',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/wrongful-conviction/id1234567890',
        spotifyUrl: 'https://open.spotify.com/show/wrongfulconviction',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Oct 2024',
        startHereNote: 'Recent episodes cover the ongoing appeals process.',
      },
    ],
  },
  {
    id: 'case_023',
    title: 'The Preppy Murder: Robert Chambers',
    summary:
      'In 1986, 18-year-old Jennifer Levin was found strangled in Central Park. The subsequent trial of Robert Chambers became a flashpoint for debates about victim-blaming and media coverage of sexual violence.',
    tags: ['Homicide', 'New York', 'Trial', '1980s', 'Media Coverage'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: 'Pre1990',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A missing person case that became a window into the failures of the system meant to protect the vulnerable.",
    perfectFor: ['Missing persons fans', 'Justice seekers', 'Commute'],
    contentNotes: ['Missing person', 'Systemic failures', 'Some graphic content'],
    podcasts: [
      {
        podcastName: 'American Scandal',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/american-scandal/id1474672641',
        spotifyUrl: 'https://open.spotify.com/show/americanscandal',
        episodeCount: 4,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Aug 2022',
        startHereNote: 'Four-part series that centers Jennifer Levin\'s story.',
      },
    ],
  },
  {
    id: 'case_024',
    title: 'The Unabomber',
    summary:
      'Ted Kaczynski conducted a 17-year bombing campaign targeting universities and airlines, killing three people and injuring 23. His capture came after his brother recognized his writing in a published manifesto.',
    tags: ['Domestic Terrorism', 'Montana', 'FBI Investigation', 'Manifesto'],
    caseStatus: 'Solved',
    crimeTypes: ['SerialOffender'],
    era: 'Pre1990',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'ShockingTurns', 'ColdCaseRevived'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A financial crime that devastated a community and exposed the human cost of corporate greed.",
    perfectFor: ['Finance fans', 'Community stories', 'Commute'],
    contentNotes: ['Financial crime', 'No graphic violence', 'Community impact'],
    podcasts: [
      {
        podcastName: 'American Scandal',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/american-scandal/id1474672641',
        spotifyUrl: 'https://open.spotify.com/show/americanscandal',
        episodeCount: 5,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Apr 2022',
        startHereNote: 'Five-episode series covering the full arc of the investigation.',
      },
    ],
  },
  {
    id: 'case_025',
    title: 'The Scott Peterson Case',
    summary:
      'Scott Peterson was convicted of murdering his pregnant wife Laci and their unborn son in 2002. The case remains one of the most discussed domestic homicide cases in American legal history.',
    tags: ['Homicide', 'California', 'Trial', 'Domestic Violence'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'MediaCircus'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Dec 2024',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A wrongful conviction story that took decades to unravel, with extraordinary advocacy from the victim's family.",
    perfectFor: ['Justice seekers', 'Legal drama fans', 'Long drives'],
    contentNotes: ['Wrongful conviction', 'Courtroom focus', 'Emotional content'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: true,
        coverageEndDate: 'Jan 2025',
        startHereNote: 'Updated episode covers the recent appeal proceedings.',
      },
    ],
  },
  {
    id: 'case_026',
    title: 'The Idaho Student Murders',
    summary:
      'Four University of Idaho students were found stabbed to death in their off-campus home in November 2022. A suspect was arrested two months later and the trial is ongoing.',
    tags: ['Homicide', 'Idaho', 'College Students', 'Recent'],
    caseStatus: 'Ongoing',
    crimeTypes: ['Homicide'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'ShockingTurns'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Apr 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
  hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cult leader who built an empire on manipulation and fear, exposed through the bravery of survivors.",
    perfectFor: ['Cult obsessives', 'Psychology fans', 'Late night'],
    contentNotes: ['Cult dynamics', 'Psychological manipulation', 'Survivor testimony'],
    podcasts: [
      {
        podcastName: 'True Crime Daily',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/true-crime-daily/id1200000000',
        spotifyUrl: 'https://open.spotify.com/show/truecrimedaily',
        episodeCount: 8,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'May 2025',
        startHereNote: 'Ongoing coverage; most recent episodes cover the trial.',
      },
    ],
  },
  // ============================================================
  // Cases 027-041 (added v1.4)
  // ============================================================
  {
    id: 'case_027',
    title: 'The Watts Family Murders',
    summary:
      'In August 2018, Chris Watts strangled his pregnant wife and two young daughters in their Colorado home before burying them on an oil field. He confessed days later.',
    tags: ['Familicide', 'Colorado', 'Domestic Violence', '2010s'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '2010s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ShockingTurns', 'MediaCircus'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: true,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    hostName: 'Ashley Flowers',
    whyWeLoveIt: "A chilling case of intimate betrayal that forced a national conversation about domestic violence and the warning signs hiding in plain sight.",
    perfectFor: ['Domestic violence awareness', 'Psychology fans', 'Late night'],
    contentNotes: ['Familicide', 'Child victims', 'Domestic violence', 'Graphic details'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Aug 2018',
        startHereNote: 'Listen to both episodes back to back for the full story.',
      },
    ],
  },
  {
    id: 'case_028',
    title: 'The Disappearance of Sherri Papini',
    summary:
      'A California mother vanished in 2016 and reappeared weeks later claiming she had been kidnapped. Years later she admitted she had fabricated the entire abduction.',
    tags: ['Missing Person', 'California', 'Hoax', '2010s'],
    caseStatus: 'Solved',
    crimeTypes: ['MissingPerson'],
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'RedHerrings'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cold case that haunted a small town for decades, finally solved through the power of community memory.",
    perfectFor: ['Small town stories', 'Cold case fans', 'Commute'],
    contentNotes: ['Cold case', 'Community impact', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Your Own Backyard',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/your-own-backyard/id1474742975',
        spotifyUrl: 'https://open.spotify.com/show/1iohmBNlRooIVtukKeavRa',
        episodeCount: 1,
        coverageDepth: 'Overview',
        timeCommitment: 'Under1Hr',
        narrativeStyle: 'StraightRetelling',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Apr 2022',
        startHereNote: 'The follow-up episode after her guilty plea is the essential listen.',
      },
    ],
  },
  {
    id: 'case_029',
    title: 'The Murder of Laci Peterson',
    summary:
      'Eight-months-pregnant Laci Peterson disappeared on Christmas Eve 2002 in Modesto, California. Her husband Scott was convicted of her murder and that of their unborn son.',
    tags: ['Homicide', 'California', 'Domestic Violence', '2000s'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: '2000s',
    contentIntensity: 'CourtFocused',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Feb 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A financial fraud that exposed the dark side of the wellness industry, with victims speaking out for the first time.",
    perfectFor: ['Fraud fans', 'Wellness culture', 'Commute'],
    contentNotes: ['Financial fraud', 'No graphic violence', 'Victim testimony'],
    podcasts: [
      {
        podcastName: 'Your Own Backyard',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/your-own-backyard/id1474742975',
        spotifyUrl: 'https://open.spotify.com/show/1iohmBNlRooIVtukKeavRa',
        episodeCount: 4,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Mar 2025',
        startHereNote: 'Start at episode 1; recent episodes cover the appeal.',
      },
    ],
  },
  {
    id: 'case_030',
    title: 'The NXIVM Sex Cult',
    summary:
      'Keith Raniere built a self-help organization that secretly operated as a sex cult, branding women and keeping them as slaves. He was convicted in 2019 on federal charges.',
    tags: ['Cult', 'Sex Trafficking', 'New York', '2010s'],
    caseStatus: 'Solved',
    crimeTypes: ['Cult', 'Corruption'],
    era: '2010s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ShockingTurns', 'MediaCircus', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: true,
    coverImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80',
    hostName: 'Sarah Edmondson',
    whyWeLoveIt: "A self-help empire built on coercion, branding, and silence. The survivors who spoke out changed everything.",
    perfectFor: ['Cult obsessives', 'Psychology fans', 'Long drives'],
    contentNotes: ['Sexual assault', 'Psychological manipulation', 'Cult dynamics', 'Graphic at times'],
    podcasts: [
      {
        podcastName: 'The Vow (HBO Companion)',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-vow/id1000000001',
        spotifyUrl: 'https://open.spotify.com/show/nxivm',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Oct 2021',
        startHereNote: 'Pair with the HBO documentary for full context.',
      },
    ],
  },
  {
    id: 'case_031',
    title: 'The Disappearance of Natalee Holloway',
    summary:
      'An 18-year-old American student vanished during a graduation trip to Aruba in 2005. Joran van der Sloot was the prime suspect but was never charged in her case.',
    tags: ['Missing Person', 'Aruba', 'Unsolved', '2000s'],
    caseStatus: 'Unsolved',
    crimeTypes: ['MissingPerson', 'Homicide'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'MediaCircus', 'RedHerrings'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Jan 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A missing person case that became a symbol of the epidemic of violence against Indigenous women.",
    perfectFor: ['Missing persons fans', 'Social justice', 'Late night'],
    contentNotes: ['Missing person', 'Indigenous women', 'Some graphic content'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: true,
        coverageEndDate: 'Feb 2025',
        startHereNote: 'The 2025 update episode covers the latest developments.',
      },
    ],
  },
  {
    id: 'case_032',
    title: 'The Menendez Brothers',
    summary:
      'In 1989, brothers Lyle and Erik Menendez shot and killed their parents in their Beverly Hills mansion. Their televised trials and claims of abuse captivated the nation.',
    tags: ['Homicide', 'Beverly Hills', 'Courtroom Drama', '1990s'],
    caseStatus: 'WrongfulConviction',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'CourtFocused',
    storyMechanics: ['MediaCircus', 'ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Mar 2025',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A corruption scandal that toppled a powerful institution, told through the voices of whistleblowers who risked everything.",
    perfectFor: ['Political crime fans', 'Whistleblower stories', 'Commute'],
    contentNotes: ['Corruption', 'No graphic violence', 'Institutional failure'],
    podcasts: [
      {
        podcastName: 'Court Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/court-junkie/id1200000002',
        spotifyUrl: 'https://open.spotify.com/show/courtjunkie',
        episodeCount: 5,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'CourtFocused',
        includesRecentUpdates: true,
        coverageEndDate: 'Apr 2025',
        startHereNote: 'Recent episodes cover the 2025 resentencing hearings.',
      },
    ],
  },
  {
    id: 'case_033',
    title: 'The Murder of Gabby Petito',
    summary:
      'Aspiring travel blogger Gabby Petito vanished during a cross-country van trip in 2021. Her fiance Brian Laundrie returned home without her and later died by suicide.',
    tags: ['Homicide', 'Wyoming', 'Domestic Violence', 'Recent'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide', 'MissingPerson'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: true,
    hasDomesticViolence: true,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A serial offender case that exposed gaps in the system that allowed a predator to operate for years.",
    perfectFor: ['Procedural fans', 'Justice seekers', 'Long drives'],
    contentNotes: ['Serial offender', 'Graphic at times', 'Systemic failures'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 3,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Dec 2021',
        startHereNote: 'Start with the first episode; the three-part series tells the full story.',
      },
    ],
  },
  {
    id: 'case_034',
    title: 'The Zodiac Killer',
    summary:
      'An unidentified serial killer terrorized Northern California in the late 1960s and early 1970s, taunting police and media with coded letters. The case remains officially unsolved.',
    tags: ['Serial Killer', 'California', 'Unsolved', 'Pre-1990'],
    caseStatus: 'Unsolved',
    crimeTypes: ['Homicide', 'SerialOffender'],
    era: 'Pre1990',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings', 'ColdCaseRevived'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cult that operated under the guise of a self-help organization, with survivors sharing their stories of escape.",
    perfectFor: ['Cult obsessives', 'Psychology fans', 'Wind down'],
    contentNotes: ['Cult dynamics', 'Psychological manipulation', 'Survivor testimony'],
    podcasts: [
      {
        podcastName: 'Case File',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id1044121020',
        spotifyUrl: 'https://open.spotify.com/show/4RlCCpHJPGkuE2yfBiNJHt',
        episodeCount: 4,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jan 2022',
        startHereNote: 'Start at episode 1 of the Zodiac series for a chronological deep-dive.',
      },
    ],
  },
  {
    id: 'case_035',
    title: 'The Theranos Fraud',
    summary:
      'Elizabeth Holmes built a $9 billion blood-testing startup on a lie. When investigative journalists exposed the fraud, she was charged with federal wire fraud and convicted in 2022.',
    tags: ['Fraud', 'Silicon Valley', 'White Collar', '2010s'],
    caseStatus: 'Solved',
    crimeTypes: ['Fraud', 'Corruption'],
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['ShockingTurns', 'MediaCircus', 'NarrativeShifts'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: true,
    coverImage: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&q=80',
    hostName: 'Rebecca Jarvis',
    whyWeLoveIt: "The most audacious Silicon Valley fraud ever told, with a protagonist whose ambition and deception are equally mesmerizing.",
    perfectFor: ['Finance fans', 'Tech culture', 'Commute'],
    contentNotes: ['Financial fraud', 'No graphic violence', 'Complex corporate themes'],
    podcasts: [
      {
        podcastName: 'The Dropout',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/the-dropout/id1449500734',
        spotifyUrl: 'https://open.spotify.com/show/7fOqBEjLzVtmKUhxHxKSKr',
        episodeCount: 6,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'Interview',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jan 2022',
        startHereNote: 'The original podcast that broke the story wide open.',
      },
    ],
  },
  {
    id: 'case_036',
    title: 'The Murder of JonBenet Ramsey',
    summary:
      'Six-year-old beauty queen JonBenet Ramsey was found murdered in her family home in Boulder, Colorado on Christmas Day 1996. The case remains officially unsolved.',
    tags: ['Cold Case', 'Colorado', 'Child Victim', '1990s'],
    caseStatus: 'Unsolved',
    crimeTypes: ['Homicide'],
    era: '1990s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings', 'MediaCircus'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Jan 2025',
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A kidnapping case that changed international law on child abduction, told with extraordinary detail.",
    perfectFor: ['Historical cases', 'Legal drama fans', 'Commute'],
    contentNotes: ['Kidnapping', 'Child victim', 'International focus'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Feb 2025',
        startHereNote: 'The 2025 episode covers the latest DNA developments.',
      },
    ],
  },
  {
    id: 'case_037',
    title: 'The Disappearance of Asha Degree',
    summary:
      'Nine-year-old Asha Degree walked out of her home alone in the middle of a stormy night in North Carolina in 2000. She has never been found and the case remains open.',
    tags: ['Missing Person', 'North Carolina', 'Child Victim', '2000s'],
    caseStatus: 'Unsolved',
    crimeTypes: ['MissingPerson'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'RedHerrings'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A financial scandal that brought down a major corporation and sent shockwaves through the industry.",
    perfectFor: ['Finance fans', 'Corporate crime', 'Commute'],
    contentNotes: ['Financial crime', 'No graphic violence', 'Corporate focus'],
    podcasts: [
      {
        podcastName: 'Casefile',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id1044121020',
        spotifyUrl: 'https://open.spotify.com/show/4RlCCpHJPGkuE2yfBiNJHt',
        episodeCount: 1,
        coverageDepth: 'InDepth',
        timeCommitment: 'Under1Hr',
        narrativeStyle: 'StraightRetelling',
        tone: 'Narrative',
        includesRecentUpdates: false,
        coverageEndDate: 'Aug 2019',
        startHereNote: 'A single comprehensive episode covering the full case.',
      },
    ],
  },
  {
    id: 'case_038',
    title: 'The BTK Killer',
    summary:
      'Dennis Rader murdered ten people in Wichita, Kansas between 1974 and 1991, calling himself BTK (Bind, Torture, Kill). He evaded capture for decades before his arrest in 2005.',
    tags: ['Serial Killer', 'Kansas', 'Cold Case', 'Pre-1990'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide', 'SerialOffender'],
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: ['ColdCaseRevived', 'ShockingTurns', 'KeepsYouGuessing'],
    recentDevelopments: false,
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A cold case that was cracked by a retired detective who spent decades pursuing justice for the victim.",
    perfectFor: ['Cold case fans', 'Procedural fans', 'Late night'],
    contentNotes: ['Cold case', 'Homicide', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Casefile',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id1044121020',
        spotifyUrl: 'https://open.spotify.com/show/4RlCCpHJPGkuE2yfBiNJHt',
        episodeCount: 3,
        coverageDepth: 'Exhaustive',
        timeCommitment: '3PlusHrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Jun 2021',
        startHereNote: 'Three-part series; start at part one for the full chronology.',
      },
    ],
  },
  {
    id: 'case_039',
    title: 'The Murder of Ahmaud Arbery',
    summary:
      'Ahmaud Arbery, a 25-year-old Black man, was shot and killed while jogging in a Georgia neighborhood in February 2020. Three white men were convicted of murder in 2021.',
    tags: ['Homicide', 'Georgia', 'Racial Violence', 'Recent'],
    caseStatus: 'Solved',
    crimeTypes: ['Homicide'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns'],
    recentDevelopments: false,
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A case that sparked a national reckoning on racial violence, told with unflinching clarity and respect for the victim.",
    perfectFor: ['Social justice', 'Recent cases', 'Commute'],
    contentNotes: ['Racial violence', 'Homicide', 'Moderate intensity'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Investigative',
        includesRecentUpdates: false,
        coverageEndDate: 'Dec 2021',
        startHereNote: 'Two-part coverage; the second episode covers the verdict.',
      },
    ],
  },
  {
    id: 'case_040',
    title: 'The Disappearance of Madeleine McCann',
    summary:
      'Three-year-old Madeleine McCann vanished from her family holiday apartment in Portugal in 2007. Despite a global search, she has never been found and the case remains open.',
    tags: ['Missing Person', 'Portugal', 'Child Victim', '2000s'],
    caseStatus: 'Unsolved',
    crimeTypes: ['MissingPerson'],
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['KeepsYouGuessing', 'MediaCircus', 'RedHerrings'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Feb 2025',
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "One of the most searched missing persons cases in history, still unsolved after nearly two decades of global scrutiny.",
    perfectFor: ['Missing persons fans', 'Cold case obsessives', 'Long drives'],
    contentNotes: ['Child victim', 'Unsolved', 'Media circus themes'],
    podcasts: [
      {
        podcastName: 'Casefile',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/casefile-true-crime/id1044121020',
        spotifyUrl: 'https://open.spotify.com/show/4RlCCpHJPGkuE2yfBiNJHt',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'EpisodeByEpisode',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Mar 2025',
        startHereNote: 'The 2025 update covers the latest suspect developments.',
      },
    ],
  },
  {
    id: 'case_041',
    title: 'The Murder of Breonna Taylor',
    summary:
      'Breonna Taylor, a 26-year-old emergency medical technician, was shot and killed by Louisville police officers who executed a no-knock warrant at her apartment in March 2020.',
    tags: ['Homicide', 'Kentucky', 'Police Shooting', 'Recent'],
    caseStatus: 'WrongfulConviction',
    crimeTypes: ['Homicide'],
    era: 'Recent',
    contentIntensity: 'LightDiscussion',
    storyMechanics: ['MediaCircus', 'ShockingTurns', 'NarrativeShifts'],
    recentDevelopments: true,
    lastDevelopmentDate: 'Oct 2024',
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    coverImage: 'https://images.unsplash.com/photo-1510784722466-f2aa240a3b2b?w=800&q=80',
    hostName: 'Various hosts',
    whyWeLoveIt: "A case that became a catalyst for a movement, told with the gravity and urgency it deserves.",
    perfectFor: ['Social justice', 'Recent cases', 'Justice seekers'],
    contentNotes: ['Police shooting', 'Systemic failures', 'Emotional content'],
    podcasts: [
      {
        podcastName: 'Crime Junkie',
        applePodcastsUrl: 'https://podcasts.apple.com/us/podcast/crime-junkie/id1322200189',
        spotifyUrl: 'https://open.spotify.com/show/2VRS1IJCTn2Nlkg33ZVfkM',
        episodeCount: 2,
        coverageDepth: 'InDepth',
        timeCommitment: '1to3Hrs',
        narrativeStyle: 'StraightRetelling',
        tone: 'Investigative',
        includesRecentUpdates: true,
        coverageEndDate: 'Nov 2024',
        startHereNote: 'The 2024 episode covers the federal charges and verdict.',
      },
    ],
  },
];

// ============================================================
// Vibe Categories for Onboarding
// ============================================================

export const VIBE_CATEGORIES: VibeCategory[] = [
  {
    id: 'cold_cases',
    label: 'Cold Case Obsessive',
    description: 'Unsolved mysteries that keep you up at night',
    emoji: '🔍',
    crimeTypes: ['MissingPerson', 'Homicide'],
  },
  {
    id: 'psychology',
    label: 'Psychology & Profiling',
    description: 'Understanding the minds behind the crimes',
    emoji: '🧠',
    crimeTypes: ['SerialOffender'],
  },
  {
    id: 'wrongful',
    label: 'Justice & Wrongful Convictions',
    description: 'When the system fails and advocates fight back',
    emoji: '⚖️',
    crimeTypes: ['Homicide'],
  },
  {
    id: 'cults',
    label: 'Cults & Manipulation',
    description: 'How ordinary people get drawn into extraordinary darkness',
    emoji: '🕯️',
    crimeTypes: ['Cult', 'Corruption'],
  },
  {
    id: 'missing',
    label: 'Missing Persons',
    description: 'Stories of the disappeared and those who search for them',
    emoji: '🗺️',
    crimeTypes: ['MissingPerson'],
  },
  {
    id: 'fraud',
    label: 'Fraud & White Collar Crime',
    description: 'The crimes that happen in boardrooms, not back alleys',
    emoji: '💼',
    crimeTypes: ['Fraud', 'Corruption'],
  },
  {
    id: 'small_town',
    label: 'Small-Town Secrets',
    description: 'When the quiet places hide the darkest stories',
    emoji: '🏡',
    crimeTypes: ['Homicide', 'MissingPerson'],
  },
  {
    id: 'courtroom',
    label: 'Courtroom Drama',
    description: 'Trials, verdicts, and the fight for justice in the courtroom',
    emoji: '🏛️',
    crimeTypes: ['Homicide', 'Fraud'],
  },
  {
    id: 'intimate_betrayal',
    label: 'Intimate Betrayal',
    description: 'Crimes committed by those closest to the victim',
    emoji: '💔',
    crimeTypes: ['Homicide'],
  },
  {
    id: 'survivor_stories',
    label: 'Survivor Stories',
    description: 'Accounts from those who lived through it and fought back',
    emoji: '🌿',
    crimeTypes: ['Homicide', 'MissingPerson'],
  },
];
