/**
 * Seed script: Top 15 verified true crime cases.
 * All eras, flags, and summaries have been human-verified.
 * Summaries are spoiler-free — no perpetrator named, no outcome stated.
 * Run: node scripts/seed-cases.mjs
 */
import mysql from 'mysql2/promise';

const url = process.env.DATABASE_URL;
if (!url) throw new Error('DATABASE_URL not set');

const conn = await mysql.createConnection(url);

const cases = [
  {
    id: 'case_idaho4',
    title: 'The Idaho Four',
    summary: 'Four University of Idaho students were found murdered in their off-campus home in November 2022, setting off one of the most intensely followed investigations in recent true crime history.',
    tags: 'College Students,Moscow Idaho,Knife Attack,Recent Investigation',
    caseStatus: 'Ongoing',
    crimeTypes: JSON.stringify(['Homicide']),
    era: 'Recent',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['MediaCircus', 'ShockingTurns', 'KeepsYouGuessing']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: true,
    lastDevelopmentDate: '2025',
    coverImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
    whyWeLoveIt: 'The case that defined true crime in 2022-2023 — a campus tragedy with a suspect caught through meticulous digital forensics.',
    perfectFor: JSON.stringify(['Current events followers', 'Forensic science fans', 'Court watchers']),
    contentNotes: JSON.stringify(['Crime scene details', 'Ongoing trial coverage', 'Victim-centered reporting']),
    curatorVerified: true,
  },
  {
    id: 'case_gabby_petito',
    title: 'Gabby Petito',
    summary: 'A 22-year-old travel blogger disappeared during a cross-country van trip in 2021, sparking a massive social media-driven search and raising urgent questions about missing persons reporting disparities.',
    tags: 'Missing Person,Van Life,Social Media,Wyoming',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide', 'MissingPerson']),
    era: 'Recent',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['MediaCircus', 'ShockingTurns', 'RedHerrings']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    whyWeLoveIt: 'The case that forced a national conversation about which missing persons receive media attention — and why.',
    perfectFor: JSON.stringify(['Social justice listeners', 'Missing persons advocates', 'Documentary fans']),
    contentNotes: JSON.stringify(['Domestic violence context', 'Social media footage', 'Missing white woman syndrome discussion']),
    curatorVerified: true,
  },
  {
    id: 'case_jonbenet',
    title: 'JonBenét Ramsey',
    summary: 'A six-year-old beauty pageant contestant was found murdered in her family\'s Boulder, Colorado home on the morning after Christmas 1996, in a case that has never been officially solved.',
    tags: 'Cold Case,Child Victim,Boulder Colorado,Unsolved',
    caseStatus: 'ColdCase',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '1990s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['KeepsYouGuessing', 'RedHerrings', 'MediaCircus']),
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&q=80',
    whyWeLoveIt: 'Nearly three decades of investigation, competing theories, and DNA evidence that keeps this case alive in the public consciousness.',
    perfectFor: JSON.stringify(['Cold case obsessives', 'DNA evidence fans', 'Long-form deep divers']),
    contentNotes: JSON.stringify(['Child victim — hard filter on by default', 'Sexual assault content', 'Decades of media coverage']),
    curatorVerified: true,
  },
  {
    id: 'case_golden_state_killer',
    title: 'The Golden State Killer',
    summary: 'A serial offender terrorized California communities through the 1970s and 1980s before going silent for decades, ultimately identified in 2018 through a groundbreaking use of genealogical DNA evidence.',
    tags: 'Cold Case,DNA Evidence,Serial Offender,California,Genealogy',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['SerialOffender', 'Homicide']),
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['ColdCaseRevived', 'ShockingTurns', 'RedHerrings']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    whyWeLoveIt: 'The genealogical DNA breakthrough that cracked this case is one of the most gripping detective stories ever told.',
    perfectFor: JSON.stringify(['Cold case obsessives', 'True crime veterans', 'Forensic science fans']),
    contentNotes: JSON.stringify(['Sexual assault content', 'Detailed crime scenes', 'Decades of investigation']),
    curatorVerified: true,
  },
  {
    id: 'case_laci_peterson',
    title: 'Laci Peterson',
    summary: 'A pregnant woman disappeared on Christmas Eve 2002 from Modesto, California, in a case that became one of the most watched criminal trials of the early 2000s.',
    tags: 'Pregnant Victim,Modesto California,High-Profile Trial,2000s',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '2000s',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['MediaCircus', 'ShockingTurns']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    whyWeLoveIt: 'A foundational true crime case that defined the genre for a generation — and sparked urgent conversations about intimate partner violence.',
    perfectFor: JSON.stringify(['Court watchers', 'Foundational case listeners', 'Domestic violence awareness']),
    contentNotes: JSON.stringify(['Intimate partner violence', 'Media saturation', 'Trial coverage']),
    curatorVerified: true,
  },
  {
    id: 'case_casey_anthony',
    title: 'Casey Anthony',
    summary: 'A two-year-old girl was reported missing in 2008 in Orlando, Florida, leading to a nationally televised trial that divided the country over questions of evidence, motherhood, and reasonable doubt.',
    tags: 'High-Profile Trial,Florida,Acquittal,Media Circus',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '2000s',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['MediaCircus', 'ShockingTurns', 'KeepsYouGuessing']),
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    whyWeLoveIt: 'The trial that made true crime a national obsession — and raised lasting questions about how we evaluate evidence and motherhood.',
    perfectFor: JSON.stringify(['Court watchers', 'Controversial verdict fans', 'Media analysis']),
    contentNotes: JSON.stringify(['Child victim — hard filter on by default', 'Contested verdict', 'Heavy media coverage']),
    curatorVerified: true,
  },
  {
    id: 'case_amanda_knox',
    title: 'Amanda Knox',
    summary: 'An American student studying abroad in Perugia, Italy was accused of murdering her British roommate in 2007, leading to a decade-long international legal battle that questioned evidence, media bias, and prosecutorial conduct.',
    tags: 'Wrongful Conviction,Italy,International,Media Bias',
    caseStatus: 'WrongfulConviction',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '2000s',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['WrongfulConviction', 'MediaCircus', 'RedHerrings']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&q=80',
    whyWeLoveIt: 'A wrongful conviction story that exposes how media narratives, cultural bias, and flawed forensics can destroy an innocent person\'s life.',
    perfectFor: JSON.stringify(['Wrongful conviction advocates', 'International cases', 'Legal system critics']),
    contentNotes: JSON.stringify(['Sexual assault content', 'International legal system', 'Media bias analysis']),
    curatorVerified: true,
  },
  {
    id: 'case_gypsy_rose',
    title: 'Gypsy Rose Blanchard',
    summary: 'A young woman who spent her entire childhood as a medical prisoner — her mother fabricating serious illnesses to control her — eventually took a desperate action that sent shockwaves through the medical and true crime communities.',
    tags: 'Medical Abuse,Munchausen by Proxy,Missouri,Female Perpetrator',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide', 'Fraud']),
    era: '2010s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['ShockingTurns', 'NarrativeShifts', 'KeepsYouGuessing']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: true,
    recentDevelopments: true,
    lastDevelopmentDate: '2024',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    whyWeLoveIt: 'One of the most morally complex cases in true crime — a victim who became a perpetrator, and a story that forces you to question everything you think you know about guilt.',
    perfectFor: JSON.stringify(['Psychological deep divers', 'Medical abuse awareness', 'Morally complex cases']),
    contentNotes: JSON.stringify(['Medical abuse and neglect', 'Psychological manipulation', 'Complex victim/perpetrator dynamic']),
    curatorVerified: true,
  },
  {
    id: 'case_delphi_murders',
    title: 'The Delphi Murders',
    summary: 'Two teenage girls were murdered on a hiking trail in Delphi, Indiana in 2017, leaving behind a haunting audio recording of their attacker that drove a six-year community investigation before a suspect was finally arrested.',
    tags: 'Cold Case,Indiana,Audio Evidence,Teen Victims,Solved 2022',
    caseStatus: 'Ongoing',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '2010s',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['ColdCaseRevived', 'KeepsYouGuessing', 'ShockingTurns']),
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: true,
    lastDevelopmentDate: '2025',
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    whyWeLoveIt: 'The audio recording that captivated a nation — and a community that refused to let their girls be forgotten for six years.',
    perfectFor: JSON.stringify(['Cold case followers', 'Community investigation stories', 'Audio evidence cases']),
    contentNotes: JSON.stringify(['Child victims — hard filter on by default', 'Sexual assault content', 'Audio recording of attacker']),
    curatorVerified: true,
  },
  {
    id: 'case_maura_murray',
    title: 'The Disappearance of Maura Murray',
    summary: 'A 21-year-old college student vanished after a car accident on a rural New Hampshire road in 2004, leaving behind a mystery that investigators and amateur sleuths have pursued for over two decades.',
    tags: 'Missing Person,Unsolved,New Hampshire,College Student',
    caseStatus: 'Unsolved',
    crimeTypes: JSON.stringify(['MissingPerson']),
    era: '2000s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: JSON.stringify(['KeepsYouGuessing', 'RedHerrings']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
    whyWeLoveIt: 'Two decades of amateur sleuthing, dead ends, and haunting unanswered questions make this one of the most compelling missing persons cases.',
    perfectFor: JSON.stringify(['Missing persons advocates', 'Amateur sleuth stories', 'Cold case obsessives']),
    contentNotes: JSON.stringify(['Unsolved disappearance', 'Speculation-heavy coverage', 'No confirmed foul play']),
    curatorVerified: true,
  },
  {
    id: 'case_scott_peterson',
    title: 'Scott Peterson',
    summary: 'A fertilizer salesman in Modesto, California was convicted of murdering his pregnant wife in a case built largely on circumstantial evidence, wiretaps, and a secret affair.',
    tags: 'Circumstantial Evidence,California,High-Profile Trial,Intimate Partner',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '2000s',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['MediaCircus', 'ShockingTurns']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    whyWeLoveIt: 'A masterclass in how circumstantial evidence and jury psychology intersect — and a case that still sparks fierce debate.',
    perfectFor: JSON.stringify(['Court watchers', 'Circumstantial evidence cases', 'Legal debate fans']),
    contentNotes: JSON.stringify(['Intimate partner violence', 'Circumstantial evidence debate', 'Media saturation']),
    curatorVerified: true,
  },
  {
    id: 'case_btk',
    title: 'BTK: Bind, Torture, Kill',
    summary: 'A serial killer terrorized Wichita, Kansas from the 1970s through the 1990s, taunting police and media with letters before going dormant for years — and was ultimately caught through a digital forensics breakthrough in 2005.',
    tags: 'Serial Killer,Kansas,Cold Case,DNA Evidence,Self-Surrender',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['SerialOffender', 'Homicide']),
    era: 'Pre1990',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['ColdCaseRevived', 'ShockingTurns', 'KeepsYouGuessing']),
    hasChildVictim: true,
    isFamilicide: false,
    hasSexualAssault: true,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80',
    whyWeLoveIt: 'The double life of a church president and community leader who was also one of America\'s most prolific serial killers — a story about the masks people wear.',
    perfectFor: JSON.stringify(['Serial killer psychology', 'Cold case obsessives', 'Forensic science fans']),
    contentNotes: JSON.stringify(['Child victims — hard filter on by default', 'Sexual violence', 'Graphic crime details']),
    curatorVerified: true,
  },
  {
    id: 'case_adnan_syed',
    title: 'Adnan Syed',
    summary: 'A Baltimore teenager was convicted of murdering his ex-girlfriend in 1999 in a case that became the subject of the groundbreaking Serial podcast — and has since seen his conviction vacated and reinstated in a continuing legal saga.',
    tags: 'Wrongful Conviction,Serial Podcast,Baltimore,Ongoing Legal Battle',
    caseStatus: 'WrongfulConviction',
    crimeTypes: JSON.stringify(['Homicide']),
    era: '1990s',
    contentIntensity: 'CourtFocused',
    storyMechanics: JSON.stringify(['WrongfulConviction', 'KeepsYouGuessing', 'RedHerrings']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: false,
    recentDevelopments: true,
    lastDevelopmentDate: '2024',
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    whyWeLoveIt: 'The case that launched the modern true crime podcast era — and continues to evolve with new legal developments years later.',
    perfectFor: JSON.stringify(['Wrongful conviction advocates', 'Legal system deep divers', 'Serial podcast fans']),
    contentNotes: JSON.stringify(['Ongoing legal proceedings', 'Contested evidence', 'Community impact']),
    curatorVerified: true,
  },
  {
    id: 'case_chris_watts',
    title: 'Chris Watts',
    summary: 'A Colorado man confessed to murdering his pregnant wife and two young daughters in 2018 in one of the most devastating familicide cases in recent American history.',
    tags: 'Familicide,Colorado,Confession,Pregnant Victim',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Homicide']),
    era: 'Recent',
    contentIntensity: 'GraphicDetails',
    storyMechanics: JSON.stringify(['ShockingTurns']),
    hasChildVictim: true,
    isFamilicide: true,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: true,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80',
    whyWeLoveIt: 'A case that forces the hardest questions about what we miss, what we ignore, and how ordinary a monster can look.',
    perfectFor: JSON.stringify(['Domestic violence awareness', 'Psychological deep divers', 'Familicide research']),
    contentNotes: JSON.stringify(['Child victims — hard filter on by default', 'Familicide — hard filter on by default', 'Domestic violence', 'Extremely heavy content']),
    curatorVerified: true,
  },
  {
    id: 'case_elizabeth_holmes',
    title: 'Elizabeth Holmes & Theranos',
    summary: 'A Stanford dropout built a $9 billion blood-testing empire on technology that did not work, deceiving investors, patients, and the medical establishment in one of Silicon Valley\'s most spectacular frauds.',
    tags: 'Silicon Valley,Healthcare Fraud,Female Perpetrator,Corporate Crime',
    caseStatus: 'Solved',
    crimeTypes: JSON.stringify(['Fraud', 'Financial']),
    era: '2010s',
    contentIntensity: 'LightDiscussion',
    storyMechanics: JSON.stringify(['ShockingTurns', 'MediaCircus', 'NarrativeShifts']),
    hasChildVictim: false,
    isFamilicide: false,
    hasSexualAssault: false,
    hasSuicide: false,
    hasDomesticViolence: false,
    hasPsychManipulation: true,
    recentDevelopments: false,
    lastDevelopmentDate: null,
    coverImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80',
    whyWeLoveIt: 'The most compelling fraud story of the decade — a woman who weaponized ambition, charisma, and Silicon Valley\'s blind spots to deceive everyone around her.',
    perfectFor: JSON.stringify(['White collar crime fans', 'Business podcast listeners', 'Female perpetrator cases']),
    contentNotes: JSON.stringify(['Financial fraud', 'No physical violence', 'Corporate culture critique']),
    curatorVerified: true,
  },
];

// Insert cases using INSERT IGNORE to avoid duplicate errors on re-run
let inserted = 0;
let skipped = 0;

for (const c of cases) {
  try {
    const [result] = await conn.execute(
      `INSERT IGNORE INTO \`cases\` 
        (id, title, summary, tags, caseStatus, crimeTypes, era, contentIntensity, storyMechanics,
         hasChildVictim, isFamilicide, hasSexualAssault, hasSuicide, hasDomesticViolence, hasPsychManipulation,
         recentDevelopments, lastDevelopmentDate, coverImage, whyWeLoveIt, perfectFor, contentNotes, curatorVerified)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        c.id, c.title, c.summary, c.tags, c.caseStatus, c.crimeTypes, c.era,
        c.contentIntensity, c.storyMechanics,
        c.hasChildVictim, c.isFamilicide, c.hasSexualAssault, c.hasSuicide,
        c.hasDomesticViolence, c.hasPsychManipulation,
        c.recentDevelopments, c.lastDevelopmentDate ?? null,
        c.coverImage, c.whyWeLoveIt ?? null,
        c.perfectFor ?? null, c.contentNotes ?? null,
        c.curatorVerified,
      ]
    );
    if (result.affectedRows > 0) {
      console.log(`✓ Inserted: ${c.title}`);
      inserted++;
    } else {
      console.log(`→ Skipped (already exists): ${c.title}`);
      skipped++;
    }
  } catch (err) {
    console.error(`✗ Error inserting ${c.title}: ${err.message}`);
  }
}

await conn.end();
console.log(`\nDone. Inserted: ${inserted}, Skipped: ${skipped}`);
